// OpenJLPT N3 표현의 학습용 한국어 해설과 첫 번째 예문 번역.
// 원본 ID를 유지하여 원자료가 바뀌어도 빠진 항목을 검증할 수 있다.
export const n3GrammarKo: Record<string, { explanation: string; translation: string; focus: string }> = {
  'wake-da': { explanation: '이미 알고 있는 사실에서 당연한 결론을 이끌거나 새로 이해한 이유를 말한다. 「わけではない」와 구별한다.', translation: '중국에서 3년이나 살았어요? 그래서 중국어를 잘하는 거군요.', focus: 'わけですね' },
  'wake-de-wa-nai': { explanation: '앞의 내용을 전부 부정하지 않고 일부만 부정한다. 「항상·모두 그런 것은 아니다」라는 뜻으로 자주 쓴다.', translation: '요리가 싫은 것은 아니지만 매일 만들 시간이 없다.', focus: 'わけではない' },
  'wake-ga-nai': { explanation: '근거를 바탕으로 어떤 일이 일어날 가능성을 강하게 부정한다.', translation: '이렇게 열심히 연습했으니 질 리가 없다.', focus: 'わけがない' },
  'wake-ni-wa-ikanai': { explanation: '능력은 있어도 책임·상황·도리 때문에 할 수 없음을 나타낸다. 부정형은 「하지 않을 수 없다」는 뜻이 된다.', translation: '내일 중요한 회의가 있어서 쉴 수는 없다.', focus: 'わけにはいかない' },
  'mono-da': { explanation: '일반적인 이치, 과거의 습관, 강한 감탄을 나타낸다. 앞 문장의 시제와 문맥으로 의미를 구별한다.', translation: '어릴 때는 이 강에서 자주 수영하곤 했다.', focus: 'ものだ' },
  'mono-de-wa-nai': { explanation: '상식이나 도덕에 비추어 해서는 안 되는 행동을 말한다.', translation: '남의 실패를 비웃어서는 안 된다.', focus: 'ものではない' },
  'mono-mon': { explanation: '자신의 이유를 가볍게 내세우는 구어 표현이다. 「もん」은 친한 사이에서 쓴다.', translation: '“왜 안 먹어?” “피망이 싫은걸.”', focus: 'なんだもん' },
  'mono-dakara-mono-de': { explanation: '사정이나 변명을 부드럽게 설명할 때 쓴다. 개인적인 이유를 덧붙이는 느낌이 있다.', translation: '길이 너무 막혀서 약속 시간에 맞추지 못했다.', focus: 'ものだから' },
  'koto-da': { explanation: '상대에게 바람직한 행동을 조언한다. 명령보다 완곡하지만 충고하는 어감이 있다.', translation: '일본어를 잘하고 싶다면 조금씩이라도 매일 말하는 게 좋다.', focus: 'ことだ' },
  'koto-wa-nai': { explanation: '어떤 행동을 할 필요가 없다고 안심시키거나 조언할 때 쓴다.', translation: '간단한 수술이니 그렇게 걱정할 필요는 없어요.', focus: 'ことはありません' },
  'koto-ni-shite-iru': { explanation: '스스로 정한 규칙이나 습관을 지금도 계속 지키고 있음을 나타낸다.', translation: '건강을 위해 일주일에 세 번은 헬스장에 가기로 하고 있다.', focus: 'ことにしている' },
  'koto-ni-natte-iru': { explanation: '개인의 결정이 아니라 규칙·일정·합의에 따라 정해져 있는 상태를 말한다.', translation: '이 기숙사에서는 밤 11시까지 돌아오도록 되어 있다.', focus: 'ことになっている' },
  'koto-instruction': { explanation: '안내문이나 규칙에서 해야 할 일을 간결하게 지시한다. 문장 끝에 기본형 또는 부정형 뒤 「こと」를 붙인다.', translation: '보고서는 다음 주 금요일까지 제출할 것.', focus: '提出すること' },
  'you-ni-iu-you-ni-tanomu': { explanation: '상대에게 어떤 행동을 하거나 하지 말라고 전한 내용을 나타낸다. 부탁에는 「頼む」를 쓴다.', translation: '의사에게 술을 너무 많이 마시지 말라는 말을 들었다.', focus: 'ように言われた' },
  'you-to-suru': { explanation: '행동을 시도하거나 막 시작하려는 순간을 나타낸다. 동사의 의지형에 붙인다.', translation: '문을 열려고 했지만 잠겨 있어서 열리지 않았다.', focus: 'ようとした' },
  'sou-ni-nai-sou-mo-nai': { explanation: '현재 보이는 상황에서 일이 일어날 가능성이 낮다고 판단한다. 동사의 ます형 어간에 붙인다.', translation: '이 비는 저녁까지 그칠 것 같지 않다.', focus: 'そうにない' },
  'ippou-da': { explanation: '한 방향으로 변화가 계속 진행되는 것을 말한다. 좋아지는 경우에도 쓸 수 있다.', translation: '이 도시의 인구는 계속 줄어들기만 한다.', focus: '一方だ' },
  'ippou-de': { explanation: '같은 대상의 서로 다른 면을 대비하거나 다른 상황을 함께 설명한다.', translation: '인터넷은 편리한 한편 위험한 면도 있다.', focus: '一方で' },
  'ni-taishite': { explanation: '행동의 대상이나 비교 대상을 나타낸다. 뒤에 명사가 오면 「に対する」를 쓴다.', translation: '손님에게 그런 식으로 말해서는 안 된다.', focus: 'に対して' },
  'ni-tsuite': { explanation: '이야기·조사·공부의 주제를 나타낸다. 뒤에 명사가 오면 「についての」를 쓴다.', translation: '오늘 수업에서는 일본의 음식 문화에 관해 토론했다.', focus: 'について' },
  'ni-yotte-ni-yoru': { explanation: '행위자, 원인, 수단 또는 경우에 따른 차이를 나타낸다. 문맥에 따라 뜻을 구별한다.', translation: '이 다리는 유명한 건축가에 의해 설계되었다.', focus: 'によって' },
  'ni-yoru-to-ni-yoreba': { explanation: '전해 들은 정보의 출처를 밝힌다. 「〜そうだ」 등의 전언 표현과 자주 함께 쓴다.', translation: '일기예보에 따르면 주말에 큰 눈이 온다고 한다.', focus: 'によると' },
  'bakari-de-naku': { explanation: '한 대상에 더해 다른 대상도 해당함을 강조한다. 「だけでなく」와 뜻이 비슷하다.', translation: '이 영화는 아이들뿐만 아니라 어른들도 즐길 수 있다.', focus: 'ばかりでなく' },
  'dake-de-naku': { explanation: '하나만이 아니라 다른 것도 해당함을 나타낸다. 뒤에 「も」가 자주 온다.', translation: '이 가게는 음식이 맛있을 뿐만 아니라 가격도 저렴하다.', focus: 'だけでなく' },
  'mo-ba-mo': { explanation: '둘 이상의 행동이나 성질을 함께 나열한다. 앞뒤에 같은 종류의 말이 오는지 확인한다.', translation: '그녀는 노래도 부르고 피아노도 친다.', focus: '歌も歌えば' },
  'rashii-typical-of': { explanation: '그 대상답거나 전형적인 성질을 말한다. 전해 들은 정보의 「らしい」와 구별한다.', translation: '오늘은 봄다운 따뜻한 하루였다.', focus: '春らしい' },
  'ppoi': { explanation: '어떤 성질이 강하게 느껴지거나 그런 경향이 있음을 말한다. 일상적인 구어에서 많이 쓴다.', translation: '이 옷은 조금 어린아이 같으니 다른 것으로 하자.', focus: '子どもっぽい' },
  'teki': { explanation: '명사 뒤에 붙어 「~적」이라는 성질을 만든다. 명사를 꾸밀 때는 「的な」, 동사를 꾸밀 때는 「的に」를 쓴다.', translation: '일본의 전통적인 요리를 먹어 보고 싶다.', focus: '伝統的な' },
  'you-na-you-ni-like': { explanation: '닮은 예를 들어 「~같은·~처럼」을 나타낸다. 명사를 꾸미면 「ような」, 동작을 꾸미면 「ように」를 쓴다.', translation: '나도 당신처럼 친절한 간호사가 되고 싶어요.', focus: 'ような' },
  'marude-you-da': { explanation: '실제로는 아니지만 매우 비슷해 보임을 비유한다. 「まるで」와 함께 자주 쓴다.', translation: '이 방은 넓고 밝아서 마치 호텔 같다.', focus: 'まるでホテルのようだ' },
  'ni-chigai-nai': { explanation: '관찰한 근거를 바탕으로 거의 확실하다고 추측한다. 「かもしれない」보다 확신이 강하다.', translation: '옆집은 며칠째 불이 꺼져 있다. 가족이 여행을 떠난 것이 틀림없다.', focus: 'に違いない' },
  'ni-kimatte-iru': { explanation: '말하는 사람이 당연한 결과라고 강하게 단정한다. 구어에서 자주 쓴다.', translation: '연습도 하지 않고 경기에 나가면 질 게 뻔하다.', focus: 'に決まっている' },
  'ki-ga-suru': { explanation: '확실한 근거는 없지만 그런 느낌이나 인상이 든다고 말한다.', translation: '이 사람을 어디선가 만난 적이 있는 것 같다.', focus: '気がする' },
  'zu-ni': { explanation: '어떤 행동을 하지 않은 상태로 다음 행동을 한다. 「する」는 「せずに」가 된다.', translation: '오늘 아침은 아침을 먹지 않고 집을 나왔다.', focus: '食べずに' },
  'mama': { explanation: '상태가 바뀌지 않은 채 다음 일이 이어짐을 나타낸다. 앞의 동사 시제를 확인한다.', translation: '에어컨을 켠 채 잠들어 감기에 걸렸다.', focus: 'つけたまま' },
  'uchi-ni': { explanation: '상태가 계속되는 동안 또는 바뀌기 전에 행동하거나 변화가 생기는 것을 말한다.', translation: '젊을 때 여러 나라를 여행하는 게 좋다.', focus: '若いうちに' },
  'tokoro-ni-tokoro-e-tokoro-o': { explanation: '막 하려는 순간, 하고 있는 중, 막 끝난 때 다른 일이 겹쳐 일어남을 나타낸다.', translation: '막 외출하려던 참에 친구에게 전화가 왔다.', focus: 'ところに' },
  'ba-hodo': { explanation: '한쪽의 정도가 커질수록 다른 쪽도 함께 변함을 나타낸다. 같은 동사를 반복하는 형태가 많다.', translation: '일본어는 공부하면 할수록 재미있어진다.', focus: '勉強すればするほど' },
  'hodo': { explanation: '상태의 정도를 구체적인 예와 비교해 나타낸다.', translation: '어제는 서 있을 수 없을 정도로 피곤했다.', focus: 'ほど' },
  'kurai-gurai-extent': { explanation: '대략적인 정도나 최소한의 수준을 나타낸다. 정도를 나타낼 때 「ほど」와 비슷하다.', translation: '배가 너무 아파서 걸을 수 없을 정도였다.', focus: 'くらい' },
  'sae': { explanation: '극단적인 예를 들어 「그것조차」라고 강조한다.', translation: '너무 바빠서 점심을 먹을 시간조차 없었다.', focus: 'さえ' },
  'sae-ba': { explanation: '한 조건만 충족하면 다른 것은 필요 없음을 말한다.', translation: '이 앱만 있으면 어디서든 일본어를 공부할 수 있다.', focus: 'さえあれば' },
  'koso': { explanation: '다른 것이 아니라 바로 그 대상임을 강조한다.', translation: '“항상 고마워.” “아니야, 내가 더 고맙지.”', focus: 'こちらこそ' },
  'to-shite': { explanation: '역할이나 자격을 나타낸다. 「~로서」의 뜻이고 이유를 나타내지 않는다.', translation: '형은 엔지니어로서 미국 회사에서 일하고 있다.', focus: 'として' },
  'ni-totte': { explanation: '누구의 관점이나 입장에서 판단하는지를 나타낸다.', translation: '나에게 가족은 무엇보다 소중하다.', focus: 'にとって' },
  'ni-shite-wa': { explanation: '기준에서 예상한 것과 실제 결과가 다를 때 쓴다. 놀라움이나 평가가 담긴다.', translation: '처음 만든 것치고는 이 케이크가 잘 만들어졌다.', focus: 'にしては' },
  'ni-shite-mo': { explanation: '앞의 사정을 인정하더라도 뒤의 판단은 달라지지 않는다고 말한다.', translation: '바빴다고 해도 전화 한 통쯤은 할 수 있었잖아요.', focus: 'にしても' },
  'ni-kanshite-ni-kansuru': { explanation: '어떤 주제와 관련됨을 나타내는 다소 격식 있는 표현이다. 「について」와 비교한다.', translation: '새 서비스에 관해 질문이 있으신 분은 접수처로 오세요.', focus: 'に関して' },
  'ni-kurabete': { explanation: '두 대상의 차이를 비교한다. 비교 대상 뒤에 붙는다.', translation: '올여름은 작년에 비해 상당히 시원하다.', focus: 'に比べて' },
  'ni-kawatte': { explanation: '다른 사람의 역할이나 일을 대신 수행함을 나타낸다.', translation: '입원 중인 사장을 대신해 부사장이 인사말을 했다.', focus: 'に代わって' },
  'kawari-ni': { explanation: '한 행동을 하지 않고 다른 행동을 하거나, 교환·보상 관계를 나타낸다.', translation: '오늘은 밖에서 먹는 대신 집에서 카레를 만들었다.', focus: '代わりに' },
  'ni-shitagatte': { explanation: '지시·규칙에 따르거나 한 변화와 함께 다른 변화가 일어남을 나타낸다.', translation: '담당자의 지시에 따라 침착하게 대피해 주세요.', focus: 'に従って' },
  'ni-tsurete': { explanation: '한 가지가 변함에 따라 다른 것도 서서히 변한다. 자연스러운 변화에 주로 쓴다.', translation: '나이가 들수록 아침 일찍 눈이 떠지게 됐다.', focus: 'につれて' },
  'to-tomo-ni': { explanation: '사람이나 사물과 함께하거나 변화가 동시에 일어남을 나타낸다. 다소 격식 있다.', translation: '사장은 직원들과 함께 새 공장의 완공을 기뻐했다.', focus: 'とともに' },
  'tabi-ni': { explanation: '같은 일이 일어날 때마다 다른 일도 반복해서 일어남을 나타낸다.', translation: '이 사진을 볼 때마다 대학 시절이 생각난다.', focus: 'たびに' },
  'goto-ni': { explanation: '정해진 간격이나 단위마다 같은 일이 일어남을 나타낸다.', translation: '이 버스는 15분마다 출발한다.', focus: 'ごとに' },
  'saichuu-ni': { explanation: '어떤 활동이 한창 진행 중인 바로 그때 다른 일이 일어남을 나타낸다.', translation: '중요한 회의 도중에 휴대전화가 울려 버렸다.', focus: '最中に' },
  'tsuide-ni': { explanation: '원래 하려던 일을 하는 기회에 다른 일도 함께 한다.', translation: '우체국에 가는 김에 이 편지도 부쳐 줄래?', focus: 'ついでに' },
  'okage-de': { explanation: '좋은 결과의 원인에 감사하는 느낌을 담는다. 좋지 않은 결과에는 보통 「せいで」를 쓴다.', translation: '선배가 도와준 덕분에 일을 일찍 끝냈다.', focus: 'おかげで' },
  'sei-de': { explanation: '좋지 않은 결과의 원인을 탓할 때 쓴다. 좋은 결과를 말하는 「おかげで」와 구별한다.', translation: '전철이 늦어진 탓에 면접에 지각하고 말았다.', focus: 'せいで' },
  'ta-totan-ta-totan-ni': { explanation: '한 동작이 끝난 바로 그 순간 예상치 못한 일이 일어남을 나타낸다.', translation: '일어서자마자 어지럼증이 났다.', focus: 'とたんに' },
  'tara-ta': { explanation: '앞의 행동을 해 보니 예상하지 못한 사실이나 결과를 알게 됐음을 말한다.', translation: '창문을 열었더니 밖은 온통 눈으로 덮여 있었다.', focus: '開けたら' },
  'tatte-datte': { explanation: '「ても·でも」의 구어형으로, 앞의 조건이 성립해도 결과가 달라지지 않음을 나타낸다.', translation: '지금부터 서둘러도 이미 늦었어.', focus: '急いだって' },
  'nai-koto-wa-nai': { explanation: '불가능한 것은 아니지만 적극적으로 그렇다고 말하기는 어려울 때 쓴다.', translation: '매운 음식을 못 먹는 건 아니지만 별로 좋아하지 않는다.', focus: '食べられないことはない' },
  'te-shou-ga-nai-te-shikata-ga-nai': { explanation: '감정이나 신체 상태가 너무 강해 어찌할 수 없음을 나타낸다.', translation: '어제 잠을 거의 못 자서 너무 졸리다.', focus: '眠くてしょうがない' },
  'te-tamaranai': { explanation: '감정·감각이 몹시 강해서 견딜 수 없음을 나타낸다.', translation: '이 방에는 에어컨이 없어 너무 더워 견딜 수 없다.', focus: '暑くてたまらない' },
  'te-hajimete': { explanation: '앞의 일을 겪은 다음에야 비로소 중요한 사실을 깨닫거나 다른 일이 가능해짐을 말한다.', translation: '아프고 나서야 비로소 건강의 소중함을 알았다.', focus: 'なってはじめて' },
  'te-bakari-iru': { explanation: '같은 행동만 지나치게 반복한다는 불만이나 비판을 담는다.', translation: '남동생은 쉬는 날 게임만 하고 있다.', focus: 'してばかりいる' },
  'ba-ii': { explanation: '어떻게 하면 되는지 묻거나 적절한 방법을 제안한다.', translation: '“이 서류는 어디에 내면 되나요?” “2층 접수처에 내세요.”', focus: '出せばいい' },
  'baai-wa': { explanation: '어떤 상황을 가정하고 그때 적용되는 규칙이나 결과를 말한다. 안내문에서 자주 쓴다.', translation: '비가 오는 경우 경기는 취소됩니다.', focus: '場合は' },
  'to-sureba-to-shitara': { explanation: '실제 여부와 상관없이 조건을 가정해 뒤의 상황을 생각한다.', translation: '만약 복권에 1억 엔이 당첨된다면 무엇에 쓰겠습니까?', focus: 'としたら' },
  'to-shite-mo': { explanation: '설령 앞의 일이 일어나더라도 뒤의 의지나 판단은 변하지 않음을 나타낸다.', translation: '부모님이 반대하시더라도 나는 유학할 생각이다.', focus: 'としても' },
  'toka-hearsay': { explanation: '확실하지 않은 전해 들은 정보를 조심스럽게 말한다. 나열의 「とか」와 구별한다.', translation: '역 앞 서점이 이번 달에 문을 닫는다던데요. 아쉽네요.', focus: 'するとか' },
  'tte': { explanation: '「と」나 「という」를 대신하는 구어 표현으로, 전언이나 화제를 나타낸다.', translation: '그녀가 오늘은 못 온대.', focus: 'って' },
  'to-iu-koto-da': { explanation: '들은 내용을 전달하거나 앞의 말이 무엇을 뜻하는지 정리한다.', translation: '역무원 말로는 사고 때문에 전철이 한 시간쯤 멈춘다고 한다.', focus: 'ということです' },
  'to-iu-no-wa': { explanation: '용어나 앞의 내용을 화제로 삼아 뜻을 정의하고 설명한다.', translation: '“와리칸”이란 식사비 등을 모두가 똑같은 금액씩 내는 것이다.', focus: 'というのは' },
  'to-iu-yori': { explanation: '앞의 표현보다 뒤의 표현이 더 정확하다고 고쳐 말한다.', translation: '오늘은 시원하다기보다 춥다고 할 정도다.', focus: 'というより' },
  'wari-ni-wari-ni-wa': { explanation: '일반적인 기준에서 예상한 것과 다른 결과를 평가한다.', translation: '이 가게는 가격에 비해 양이 많고 맛있다.', focus: 'わりに' },
  'kuse-ni': { explanation: '앞의 사실과 어긋나는 행동을 비난하거나 불만스럽게 말한다. 상대에게 직접 쓰면 강하게 들릴 수 있다.', translation: '자기는 아무것도 하지 않으면서 남의 일에는 불평만 한다.', focus: 'くせに' },
  'kara-ni-kakete': { explanation: '시간이나 장소의 시작에서 끝까지 이어지는 대략적인 범위를 나타낸다.', translation: '오늘 밤부터 내일 아침에 걸쳐 강한 비가 오겠습니다.', focus: 'から明日の朝にかけて' },
  'buri': { explanation: '오랜 시간이 흐른 뒤 다시 일어남을 나타내거나 행동의 모습을 나타낸다.', translation: '5년 만에 고등학교 친구들을 만나 이야기가 끊이지 않았다.', focus: '五年ぶりに' },
  'kke': { explanation: '기억이 흐릿한 내용을 스스로 또는 상대에게 확인하는 구어 표현이다.', translation: '어, 회의가 몇 시부터였더라?', focus: 'だっけ' },
  'masu-you-ni': { explanation: '바라는 일이 이루어지기를 기원할 때 쓴다.', translation: '시험에 합격할 수 있기를.', focus: 'ますように' },
  'furi-o-suru': { explanation: '실제로는 그렇지 않은데 그런 척 행동한다.', translation: '어머니가 부르셨지만 못 들은 척하고 게임을 계속했다.', focus: 'ふりをして' },
  'muki-muke': { explanation: '「向き」는 성질상 잘 맞는 대상, 「向け」는 만들거나 준비할 때 겨냥한 대상을 뜻한다.', translation: '이 요리는 만들기 쉬워 초보자에게 적합하다.', focus: '初心者向きだ' },
  'gachi': { explanation: '바람직하지 않은 일이 자주 일어나는 경향을 나타낸다.', translation: '겨울이 되면 나도 모르게 집에만 있는 편이다.', focus: 'がちになる' },
  'gimi': { explanation: '상태가 조금 나타나기 시작했음을 말한다. 병이나 피로와 함께 자주 쓴다.', translation: '감기 기운이 조금 있어서 오늘은 일찍 돌아갑니다.', focus: '風邪気味' },
  'darake': { explanation: '무언가가 잔뜩 묻거나 가득한 상태를 말한다. 좋지 않은 것에 자주 쓴다.', translation: '아이들은 온몸에 진흙을 묻히고 돌아왔다.', focus: '泥だらけ' },
  'kiru-kirenai': { explanation: '「切る」는 끝까지 해냄, 「切れない」는 끝까지 할 수 없음을 나타낸다.', translation: '세 시간을 들여 긴 소설을 끝까지 다 읽었다.', focus: '読み切った' },
  'kakeru': { explanation: '행동을 시작했지만 아직 끝내지 않은 상태를 나타낸다.', translation: '읽다 만 책이 책상 위에 놓여 있다.', focus: '読みかけの' },
  'au': { explanation: '둘 이상의 사람이 서로 같은 행동을 주고받는다는 뜻을 만든다.', translation: '곤란할 때는 서로 도와줍시다.', focus: '助け合いましょう' },
  'naosu': { explanation: '잘못되거나 부족한 부분을 고쳐 다시 행동함을 나타낸다.', translation: '이름을 잘못 써서 서류를 다시 작성했다.', focus: '書き直した' },
  'zurai': { explanation: '심리적·신체적으로 하기 어렵거나 불편함을 나타낸다. 단순한 난이도의 「にくい」와 비교한다.', translation: '이 신발은 조금 작아서 걷기 불편하다.', focus: '歩きづらい' },
  'beki-da-beki-de-wa-nai': { explanation: '옳다고 생각하는 행동이나 의무를 강하게 주장한다. 윗사람에게 직접 쓰면 무례할 수 있다.', translation: '자신이 잘못했다고 생각하면 바로 사과해야 한다.', focus: '謝るべきだ' },
  'hodo-wa-nai': { explanation: '비교 대상 중에서 가장 뛰어나다고 느끼는 것을 말한다.', translation: '일을 마친 뒤 마시는 차가운 맥주만큼 맛있는 것은 없다.', focus: 'ほどおいしいものはない' },
  'shika-nai-no-choice': { explanation: '다른 선택지가 없어 결국 그 행동을 해야 함을 말한다. 「명사+しか〜ない」와 구별한다.', translation: '막차를 놓쳐서 택시를 타고 돌아갈 수밖에 없다.', focus: '帰るしかない' },
  'made-even': { explanation: '앞에서 예상한 범위를 넘어 극단적인 대상까지 포함된다고 강조한다.', translation: '요즘은 초등학생까지 스마트폰을 가지고 있다.', focus: '小学生まで' },
  'tokoro-datta': { explanation: '일이 일어날 뻔했지만 실제로는 일어나지 않았음을 나타낸다.', translation: '딴생각을 하다가 하마터면 차에 치일 뻔했다.', focus: 'ひかれるところだった' },
  'kara-to-itte': { explanation: '앞의 이유만으로 뒤의 결론을 내릴 수 없다고 말한다. 뒤에는 부분 부정이 자주 온다.', translation: '일본인이라고 해서 모두가 경어를 정확히 쓸 수 있는 것은 아니다.', focus: 'だからといって' },
  'toori-ni-doori-ni': { explanation: '방법이나 결과가 앞에서 말한 내용과 똑같음을 나타낸다. 명사에 바로 붙으면 「どおり」가 된다.', translation: '설명서에 적힌 대로 조립했는데도 제대로 작동하지 않는다.', focus: 'とおりに' },
  'nanka-nante': { explanation: '대상을 낮추어 보거나 놀라움을 나타내는 구어 표현이다. 문맥에 따라 어감이 달라진다.', translation: '저 같은 사람은 아직도 초보자예요.', focus: 'なんか' },
};

// N3 학습에 앞서 참고할 N4·N5 기본 문법의 한국어 간단 뜻.
export const prerequisiteGrammarMeanings: Record<'N4' | 'N5', Record<string, string>> = {
  N4: {
    'ageru-kureru-morau': '주다 / (내 쪽에) 주다 / 받다',
    'te-ageru': '~해 주다',
    'te-kureru': '(상대가 내 쪽에) ~해 주다',
    'te-morau': '(상대에게) ~해 받다, ~해 달라고 하다',
    'te-kudasaru-te-itadaku': '(존경) ~해 주시다 / (겸양) ~해 받다',
    'te-iku': '~해 가다, 앞으로 계속 ~하다',
    'te-kuru': '~해 오다, 지금까지 ~해 왔다',
    'te-shimau-chau': '완전히 ~해 버리다, 뜻하지 않게 ~하고 말다',
    'te-oku': '미리 ~해 두다',
    'te-miru': '시험 삼아 ~해 보다',
    'te-aru': '~해 놓은 상태이다',
    'toki': '~할 때',
    'aida-aida-ni': '~하는 동안 / ~하는 사이에',
    'sou-da-appearance': '~할 것 같다 (겉모습으로 판단)',
    'sou-da-hearsay': '~라고 한다 (전해 들음)',
    'rashii': '~인 모양이다, ~라고 한다',
    'you-da': '~인 듯하다 (근거에 따른 추측)',
    'mitai': '~인 것 같다, ~처럼 보이다 (구어)',
    'sugiru': '너무 ~하다',
    'kata': '~하는 방법',
    'chuu-juu': '~하는 중, ~내내',
    'tsumori': '~할 생각이다',
    'yotei': '~할 예정이다',
    'koto-ni-suru': '(스스로) ~하기로 하다',
    'koto-ni-naru': '(상황·결정에 따라) ~하게 되다',
    'koto-ga-dekiru': '~할 수 있다',
    'eru-rareru-potential': '~할 수 있다 (가능형)',
    'reru-rareru-passive': '~되다, ~당하다 (수동형)',
    'seru-saseru': '~하게 하다, ~하도록 허락하다 (사역형)',
    'serareru-saserareru': '~하도록 강요받다 (사역수동형)',
    'ou-you': '~하자, ~해야지 (의지형)',
    'you-to-omou': '~하려고 생각하다',
    'e-ro': '~해라 (명령형)',
    'na-prohibition': '~하지 마라 (금지)',
    'nasai': '~해라 (지시)',
    'ba': '~하면 (조건)',
    'tara': '~하면, ~했을 때',
    'nara': '~라면 (상대의 말을 받아서)',
    'to': '~하면 반드시, ~할 때마다',
    'te-mo-de-mo': '~해도, ~라도',
    'noni-although': '~인데도, ~했는데',
    'noni-purpose': '~하는 데, ~하기 위해',
    'node': '~이므로, ~해서',
    'te-reason': '~해서 (이유·원인)',
    'shi': '~하고, ~하기도 하고 (이유 나열)',
    'kedo-keredomo': '~지만, ~인데',
    'tame-ni': '~하기 위해, ~때문에',
    'you-ni': '~하도록 (목적)',
    'you-ni-suru': '~하도록 노력하다, 습관으로 삼다',
    'you-ni-naru': '~하게 되다 (능력·습관의 변화)',
    'te-hoshii': '(다른 사람이) ~해 주었으면 좋겠다',
    'tagaru': '(다른 사람이) ~하고 싶어하다',
    'garu': '(다른 사람이) ~하다고 느끼는 모습을 보이다',
    'kamo-shirenai': '~일지도 모른다',
    'darou': '~일 것이다, ~겠지',
    'hazu-da': '~일 것이다 (근거 있는 예상)',
    'hazu-ga-nai': '~일 리가 없다',
    'n-desu-no-desu': '~인 것이다 (설명·이유)',
    'ka-dou-ka': '~인지 아닌지',
    'ka-embedded-question': '~인지 (의문사 포함 간접 질문)',
    'to-omou': '~라고 생각하다',
    'to-iu-say': '~라고 말하다',
    'shika-nai': '~밖에 없다',
    'bakari': '~만, ~뿐',
    'ta-bakari': '막 ~한 참이다',
    'tokoro-da': '막 ~하려는 참이다, ~하는 중이다, 막 ~했다',
    'yasui-nikui': '~하기 쉽다 / ~하기 어렵다',
    'hajimeru-owaru-tsuzukeru': '~하기 시작하다 / 끝내다 / 계속하다',
    'dasu': '갑자기 ~하기 시작하다',
    'hodo-nai': '~만큼 ~하지는 않다',
    'nakanaka-nai': '좀처럼 ~하지 못하다',
    'zutsu': '~씩, 조금씩',
    'mo-emphasis': '~나, ~도 (수량·정도 강조)',
    'made-ni': '~까지 (기한)',
    'koto-ga-aru': '가끔 ~할 때가 있다',
    'nai-to-ikenai-nakucha': '~해야 한다 (구어)',
    'sasete-kudasai': '~하게 해 주세요',
    'sonkeigo': '상대방의 동작을 높이는 존경어',
    'kenjougo': '자기 쪽의 동작을 낮추는 겸양어',
    'o-ni-naru': '(존경) ~하시다',
    'o-suru': '(겸양) ~하다',
    'de-gozaimasu': '~입니다 (격식 있는 표현)',
    'te-mo-kamawanai': '~해도 상관없다',
    'no-koto-nominalizer': '동작·문장을 명사처럼 나타내는 「の·こと」',
    'ba-yokatta': '~했으면 좋았을 텐데 (후회)',
    'tara-dou': '~하는 게 어때?',
    'hou-ga-ii': '~하는 편이 좋다',
    'toka-toka': '~라든가 ~라든가',
    'nado': '~등, ~와 같은',
    'de-mo-suggestion': '~라도 (가벼운 제안)',
    'sa': '형용사의 정도를 나타내는 「~함」',
    'me': '~번째',
    'oki-ni': '~간격으로',
    'ku-suru-ni-suru': '~하게 만들다, ~한 상태로 바꾸다',
    'ga-suru': '(냄새·소리·맛·느낌이) 나다',
    'kana-kashira': '~일까? (혼잣말·가벼운 의문)',
    'te-kuremasen-ka-te-itadakemasen-ka': '~해 주시겠습니까? (정중한 부탁)',
    'naide': '~하지 않고',
  },
  N5: {
    'wa': '화제를 나타내는 조사 「은·는」',
    'ga-subject': '주어나 새 정보를 나타내는 조사 「이·가」',
    'o': '동작의 대상을 나타내는 조사 「을·를」',
    'ni-time': '정해진 시점을 나타내는 조사 「에」',
    'ni-destination': '도착점을 나타내는 조사 「에」',
    'ni-location': '존재하는 장소를 나타내는 조사 「에」',
    'ni-indirect-object': '상대·대상을 나타내는 조사 「에게·에」',
    'ni-frequency': '기간 안의 횟수를 나타내는 조사 「에」',
    'e': '이동 방향을 나타내는 조사 「으로·로」',
    'de-place': '행동이 일어나는 장소를 나타내는 조사 「에서」',
    'de-means': '수단·도구를 나타내는 조사 「으로·로」',
    'to-and': '빠짐없이 나열할 때 쓰는 조사 「와·과」',
    'to-with': '함께하는 상대를 나타내는 조사 「와·과」',
    'ya': '몇 가지 예를 나열하는 조사 「~나 ~나」',
    'ka-or': '선택을 나타내는 조사 「또는」',
    'mo': '추가·동일함을 나타내는 조사 「도」',
    'no': '소유·소속을 나타내는 조사 「의」',
    'kara-from': '시작점을 나타내는 조사 「부터·에서」',
    'made': '끝점을 나타내는 조사 「까지」',
    'ka-question': '질문을 만드는 종조사 「까」',
    'ne': '확인·공감을 구하는 종조사 「네요·죠」',
    'yo': '새 정보·강조를 나타내는 종조사 「요」',
    'yori': '비교 기준을 나타내는 「보다」',
    'no-hou-ga-yori': '~보다 ~쪽이 더',
    'to-to-dochira-ga': '~와 ~ 중 어느 쪽이 더',
    'no-naka-de-ga-ichiban': '~중에서 가장',
    'desu': '~입니다 (정중한 현재 표현)',
    'da': '~이다 (보통체)',
    'de-wa-arimasen-ja-nai': '~이 아닙니다 / ~이 아니다',
    'deshita': '~이었습니다',
    'masu': '~합니다 (정중한 현재·미래 표현)',
    'masen': '~하지 않습니다',
    'mashita': '~했습니다',
    'masen-deshita': '~하지 않았습니다',
    'nai': '~하지 않는다 (보통체 부정)',
    'ta': '~했다 (보통체 과거)',
    'mashou': '~합시다',
    'mashou-ka': '~할까요? (제안·도움)',
    'masen-ka': '~하지 않겠습니까? (권유)',
    'tai': '~하고 싶다',
    'ga-hoshii': '~을·를 원하다',
    'o-kudasai': '~을·를 주세요',
    'te-kudasai': '~해 주세요',
    'naide-kudasai': '~하지 말아 주세요',
    'te-mo-ii': '~해도 된다',
    'te-wa-ikenai': '~해서는 안 된다',
    'nakereba-naranai-nakute-wa-ikenai': '~해야 한다',
    'nakute-mo-ii': '~하지 않아도 된다',
    'te-iru': '~하고 있다, ~한 상태이다',
    'te': '~해서, ~하고 (행동 연결)',
    'te-kara': '~한 후에',
    'tari-tari-suru': '~하기도 하고 ~하기도 하다',
    'ta-koto-ga-aru': '~한 적이 있다',
    'mae-ni': '~하기 전에',
    'ato-de': '~한 후에',
    'nagara': '~하면서',
    'ni-iku': '~하러 가다',
    'ga-suki-ga-kirai': '~을 좋아하다 / 싫어하다',
    'ga-jouzu-ga-heta': '~을 잘하다 / 못하다',
    'ga-aru-ga-iru': '(사물·생물 등이) 있다',
    'kara-reason': '~이기 때문에',
    'ga-but': '~하지만',
    'deshou': '~일 것이다, ~이겠지',
    'ku-naru-ni-naru': '~해지다',
    'ni-suru': '~로 정하다',
    'mada-te-inai': '아직 ~하지 않았다',
    'mou-ta': '이미 ~했다',
    'amari-nai': '별로 ~하지 않다',
    'zenzen-nai': '전혀 ~하지 않다',
    'dake': '~만, ~뿐',
    'kurai-gurai': '대략 ~쯤, ~정도',
    'goro': '(시간) ~쯤',
    'nani-mo-nai-dare-mo-nai': '아무것도 ~않다 / 아무도 ~않다',
    'nani-ka-dare-ka-doko-ka': '무엇인가 / 누군가 / 어딘가',
    'kore-sore-are-dore': '이것 / 그것 / 저것 / 어느 것',
    'kono-sono-ano-dono': '이 / 그 / 저 / 어느',
    'koko-soko-asoko-doko': '여기 / 거기 / 저기 / 어디',
    'ku-nai-katta-ku-nakatta': 'い형용사의 부정·과거 활용',
    'na-na-adjective': 'な형용사의 명사 수식·서술 형태',
    'kute-de': '형용사·명사를 이어 주는 「~고」',
    'to-iu-named': '~라고 하는, ~라는 이름의',
  },
};
