// N4·N5 대표 예문은 원문과 대조하여 새로 번역했다. 자동 번역 초안은 학습 화면에 사용하지 않는다.
export type PrerequisiteGrammarDetail = { explanation: string; translation: string; focus?: string };

export const prerequisiteGrammarDetails: Record<'N4' | 'N5', Record<string, PrerequisiteGrammarDetail>> = {
  N4: {
    'ageru-kureru-morau': { explanation: 'あげる는 남에게 주고, くれる는 나 또는 내 편에게 주며, もらう는 받는 쪽에서 말한다.', translation: '나는 남동생에게 낡은 게임을 주었다.' },
    'te-ageru': { explanation: '내가 남을 위해 어떤 행동을 해 주었음을 나타낸다. 윗사람에게 직접 쓰면 생색내는 느낌이 들 수 있다.', translation: '여동생의 숙제를 도와주었다.' },
    'te-kureru': { explanation: '상대가 나 또는 내 편을 위해 행동해 주었음을 나타낸다.', translation: '친구가 이사를 도와주었다.' },
    'te-morau': { explanation: '내가 상대에게 부탁하거나 도움을 받아 어떤 행동을 받았음을 나타낸다.', translation: '선배에게 보고서를 봐 달라고 했다.' },
    'te-kudasaru-te-itadaku': { explanation: '〜てくださる는 상대의 행동을 높이고, 〜ていただく는 내가 도움받은 일을 낮추어 말한다.', translation: '선생님께서 내 작문을 고쳐 주셨다.' },
    'te-iku': { explanation: '말하는 곳에서 멀어지는 이동이나 앞으로 계속되는 변화를 나타낸다.', translation: '비가 올 것 같아서 우산을 가지고 가겠습니다.' },
    'te-kuru': { explanation: '갔다가 돌아오는 이동이나 지금까지 이어져 온 변화를 나타낸다.', translation: '잠깐 편의점에 다녀올게요.' },
    'te-shimau-chau': { explanation: '행동을 끝내거나 예상하지 못한 일을 아쉬워할 때 쓴다. 〜ちゃう는 구어체다.', translation: '전철에 우산을 두고 와 버렸다.' },
    'te-oku': { explanation: '나중을 위해 미리 해 두거나 상태를 그대로 두는 것을 말한다.', translation: '여행 전에 호텔을 예약해 두겠습니다.' },
    'te-miru': { explanation: '결과를 알아보기 위해 어떤 행동을 시험 삼아 해 본다.', translation: '이 셔츠를 입어 봐도 될까요?' },
    'te-aru': { explanation: '누군가 의도적으로 해 놓은 행동의 결과가 남아 있음을 나타낸다.', translation: '입구에 지도가 붙어 있다.' },
    'toki': { explanation: '앞말이 나타내는 시점을 가리킨다. 앞뒤 동작의 시간 관계에 주의한다.', translation: '어릴 때 이 강에서 자주 수영했다.' },
    'aida-aida-ni': { explanation: '〜間은 기간 내내, 〜間に는 그 기간 안의 어느 시점에 일어난 일을 나타낸다.', translation: '여름 방학 동안 할아버지 댁에 있었다.' },
    'sou-da-appearance': { explanation: '눈앞의 모습으로 곧 일어날 일이나 겉보기에 드러나는 상태를 추측한다.', translation: '그 카레, 매워 보이네.' },
    'sou-da-hearsay': { explanation: '다른 사람이나 매체에서 들은 내용을 전한다. 겉모습을 보고 추측하는 〜そうだ와 접속이 다르다.', translation: '일기예보에 따르면 내일 눈이 온다고 합니다.' },
    'rashii': { explanation: '들은 정보나 정황을 근거로 그럴 듯하다고 판단한다.', translation: '역 근처에 새 카페가 생긴 모양이다.' },
    'you-da': { explanation: '관찰이나 정보를 바탕으로 상황을 추측한다. 비유를 나타낼 때도 쓴다.', translation: '아무도 없는 것 같네요.' },
    'mitai': { explanation: '〜ようだ와 뜻이 비슷한 일상적인 표현으로, 보고 들은 정황에서 추측한다.', translation: '옆방에 누군가 온 것 같아.' },
    'sugiru': { explanation: '정도를 넘어서 지나치게 행동하거나 어떤 상태가 됨을 나타낸다.', translation: '어젯밤에 너무 많이 마셔서 머리가 아프다.' },
    'kata': { explanation: '동사 ます형 어간에 붙여 방법이나 방식을 나타낸다.', translation: '이 기계의 사용법을 알려 주세요.' },
    'chuu-juu': { explanation: '동작이나 기간이 진행 중이거나 그 범위 전체에 걸쳐 있음을 나타낸다.', translation: '아버지는 지금 통화 중이세요.' },
    'tsumori': { explanation: '말하는 사람의 계획이나 의도를 나타낸다.', translation: '여름 방학에는 홋카이도를 여행할 생각입니다.' },
    'yotei': { explanation: '이미 잡혀 있는 일정이나 계획을 말한다.', translation: '다음 달에 오사카로 이사할 예정입니다.' },
    'koto-ni-suru': { explanation: '자신의 의지로 무엇을 하기로 결정한다.', translation: '건강을 위해 매일 아침 걷기로 했다.' },
    'koto-ni-naru': { explanation: '합의나 외부 사정에 따라 어떤 일이 정해진다.', translation: '내년 봄부터 나고야 매장에서 일하게 되었습니다.' },
    'koto-ga-dekiru': { explanation: '동작을 할 능력이나 허용된 가능성을 나타낸다.', translation: '이 도서관에서는 책을 2주 동안 빌릴 수 있습니다.' },
    'eru-rareru-potential': { explanation: '동사를 가능형으로 바꾸어 할 수 있는 능력이나 가능성을 나타낸다.', translation: '나는 한자를 200자 정도 읽을 수 있습니다.' },
    'reru-rareru-passive': { explanation: '행동을 당하거나 받는 쪽을 주어로 두는 수동형이다.', translation: '선생님께 작문을 칭찬받았습니다.' },
    'seru-saseru': { explanation: '다른 사람에게 행동을 시키거나 허락하는 사역형이다.', translation: '어머니는 매일 남동생에게 채소를 먹게 한다.' },
    'serareru-saserareru': { explanation: '다른 사람 때문에 원치 않는 행동을 하게 되었음을 나타내는 사역수동형이다.', translation: '어릴 때 어머니 때문에 매일 피아노를 연습해야 했다.' },
    'ou-you': { explanation: '동사의 의지형으로 자신의 결심이나 함께하자는 제안을 나타낸다.', translation: '피곤하네. 조금 쉬자.' },
    'you-to-omou': { explanation: '동사의 의지형에 붙여 하려고 생각하고 있는 계획을 말한다.', translation: '올여름에는 바다에 가려고 생각하고 있습니다.', focus: '行こうと思っています' },
    'e-ro': { explanation: '상대에게 직접 행동을 명령하는 강한 표현이다. 관계와 상황을 가려 쓴다.', translation: '빨리 일어나! 지각하겠어.' },
    'na-prohibition': { explanation: '동사 사전형 뒤에 な를 붙여 강하게 금지한다.', translation: '위험하니까 이 강에서는 수영하지 마.' },
    'nasai': { explanation: '윗사람이 아랫사람에게 지시할 때 자주 쓰는 명령 표현이다.', translation: '벌써 9시야. 빨리 자렴.' },
    'ba': { explanation: '조건이 충족되면 뒤의 결과가 성립함을 나타낸다.', translation: '이 길을 곧장 가면 역에 도착합니다.' },
    'tara': { explanation: '가정 조건이나 앞의 일이 끝난 뒤를 나타낸다.', translation: '역에 도착하면 전화해 주세요.' },
    'nara': { explanation: '상대가 꺼낸 화제나 이미 제시된 상황을 조건으로 삼는다.', translation: '교토에 갈 거라면 가을이 좋아요.' },
    'to': { explanation: '어떤 조건에서 자연스럽거나 반복적으로 생기는 결과를 나타낸다.', translation: '이 버튼을 누르면 차가 나옵니다.' },
    'te-mo-de-mo': { explanation: '조건이 달라도 뒤의 결과가 유지됨을 나타낸다.', translation: '비가 와도 시합은 열립니다.' },
    'noni-although': { explanation: '예상과 다른 결과에 놀라거나 아쉬워하며 앞뒤 내용을 대비한다.', translation: '열심히 공부했는데 시험에 떨어지고 말았다.' },
    'noni-purpose': { explanation: '어떤 용도나 목적에 적합한지 평가할 때 쓴다.', translation: '이 가방은 여행 갈 때 편리합니다.' },
    'node': { explanation: '이유나 원인을 비교적 부드럽고 객관적으로 설명한다.', translation: '머리가 아파서 오늘은 일찍 돌아갑니다.' },
    'te-reason': { explanation: '앞의 일 때문에 뒤의 감정이나 결과가 생겼음을 나타낸다.', translation: '뉴스를 듣고 깜짝 놀랐습니다.' },
    'shi': { explanation: '여러 이유나 특징을 나란히 들거나 덧붙인다.', translation: '이 방은 넓고 역에서도 가까워서 아주 마음에 듭니다.' },
    'kedo-keredomo': { explanation: '앞뒤 내용을 대조하거나 말끝을 부드럽게 남긴다.', translation: '이 가게는 비싸지만 음식이 맛있다.' },
    'tame-ni': { explanation: '의지를 가지고 달성하려는 목적을 나타낸다.', translation: '일본 대학에 들어가기 위해 매일 공부하고 있습니다.' },
    'you-ni': { explanation: '가능하게 만들거나 그런 상태가 되도록 하는 목적을 나타낸다.', translation: '뒤에 있는 사람에게도 들리도록 큰 목소리로 말해 주세요.' },
    'you-ni-suru': { explanation: '스스로 노력해 어떤 행동을 습관으로 삼는다.', translation: '매일 채소를 먹으려고 하고 있습니다.' },
    'you-ni-naru': { explanation: '능력이나 습관에 변화가 생긴 결과를 나타낸다.', translation: '연습해서 자전거를 탈 수 있게 되었습니다.' },
    'te-hoshii': { explanation: '다른 사람이 어떤 행동을 해 주기를 바란다.', translation: '조금만 더 천천히 말해 주셨으면 합니다.' },
    'tagaru': { explanation: '제삼자가 무엇을 하고 싶어 하는 듯한 모습을 나타낸다.', translation: '아이들은 밖에서 놀고 싶어 한다.' },
    'garu': { explanation: '제삼자의 감정이 행동이나 표정으로 드러남을 나타낸다.', translation: '여동생은 어두운 곳을 무서워한다.' },
    'kamo-shirenai': { explanation: '확신하지 못하는 가능성을 조심스럽게 말한다.', translation: '오후부터 비가 올지도 모릅니다.' },
    'darou': { explanation: '상황을 바탕으로 그럴 것이라고 추측한다.', translation: '내일은 아마 맑을 것이다.' },
    'hazu-da': { explanation: '알고 있는 근거에 비추어 당연히 그럴 것으로 예상한다.', translation: '짐은 내일 도착할 것이다.' },
    'hazu-ga-nai': { explanation: '근거를 바탕으로 그럴 가능성이 없다고 강하게 판단한다.', translation: '그렇게 성실한 사람이 거짓말을 할 리가 없다.' },
    'n-desu-no-desu': { explanation: '상황의 배경을 설명하거나 상대에게 사정을 물을 때 쓴다.', translation: '무슨 일이에요? 안색이 안 좋아요.' },
    'ka-dou-ka': { explanation: '두 가능성 중 어느 쪽인지 모를 때 「~인지 아닌지」를 나타낸다.', translation: '내일 갈 수 있을지 아직 모르겠습니다.' },
    'ka-embedded-question': { explanation: '의문사를 포함한 질문을 문장 속의 한 부분으로 만든다.', translation: '회의가 몇 시에 시작하는지 알려 주세요.' },
    'to-omou': { explanation: '자신의 생각이나 판단을 인용해 말한다.', translation: '이 영화는 분명 인기를 끌 거라고 생각한다.' },
    'to-iu-say': { explanation: '누군가 한 말을 인용해서 전한다.', translation: '선생님은 「내일 시험이 있습니다」라고 말씀하셨다.', focus: 'と言いました' },
    'shika-nai': { explanation: '적은 수량이나 범위를 강조하며 반드시 부정형과 함께 쓴다.', translation: '지갑에 500엔밖에 없다.', focus: 'しかない' },
    'bakari': { explanation: '같은 행동이나 대상에 치우쳐 있음을 나타낸다.', translation: '남동생은 고기만 먹고 채소는 먹지 않는다.' },
    'ta-bakari': { explanation: '어떤 일이 일어난 지 얼마 되지 않았음을 화자의 감각으로 말한다.', translation: '일본에 온 지 얼마 안 돼서 아직 일본어를 잘 모릅니다.' },
    'tokoro-da': { explanation: '동사 형태에 따라 막 하려는 중·하는 중·막 마친 상태를 나타낸다.', translation: '지금 막 나가려던 참입니다.' },
    'yasui-nikui': { explanation: '동사 ます형 어간에 붙여 동작하기 쉬운지 어려운지 나타낸다.', translation: '이 펜은 쓰기 편합니다.' },
    'hajimeru-owaru-tsuzukeru': { explanation: '동작의 시작·완료·지속을 동사 뒤에 덧붙인다.', translation: '작년부터 기타를 배우기 시작했습니다.', focus: '習い始めました' },
    'dasu': { explanation: '동작이 갑자기 시작됨을 나타낸다.', translation: '아기가 갑자기 울기 시작했다.', focus: '泣き出した' },
    'hodo-nai': { explanation: '비교 대상만큼의 정도에는 이르지 못함을 나타낸다.', translation: '올여름은 작년만큼 덥지 않다.', focus: 'ほど暑くない' },
    'nakanaka-nai': { explanation: '기대와 달리 일이 쉽게 실현되지 않음을 나타낸다.', translation: '버스가 좀처럼 오지 않는다.', focus: 'なかなか来ない' },
    'zutsu': { explanation: '같은 수량씩 나누거나 일정한 간격으로 반복함을 나타낸다.', translation: '사람마다 사과를 두 개씩 나누어 주었다.' },
    'mo-emphasis': { explanation: '예상보다 많거나 큰 수량을 강조한다.', translation: '어제는 무려 열 시간이나 자 버렸다.' },
    'made-ni': { explanation: '그 시점보다 늦지 않게 행동해야 하는 기한을 나타낸다.', translation: '보고서는 금요일까지 제출해 주세요.' },
    'koto-ga-aru': { explanation: '같은 상황에서 가끔 일어나는 일을 말한다.', translation: '바쁠 때는 아침밥을 먹지 않을 때가 있습니다.' },
    'nai-to-ikenai-nakucha': { explanation: '꼭 해야 하는 의무를 나타낸다. 〜なくちゃ는 편한 구어체다.', translation: '내일은 일찍 일어나야 해서 이제 자야 한다.' },
    'sasete-kudasai': { explanation: '상대에게 자신의 행동을 허락해 달라고 정중히 요청한다.', translation: '잠깐 생각할 시간을 주세요.' },
    'sonkeigo': { explanation: '상대나 높일 사람의 행동을 특별한 존경 표현으로 말한다.', translation: '사장님은 몇 시쯤 오십니까?', focus: 'いらっしゃいます' },
    'kenjougo': { explanation: '자기 쪽의 행동을 낮추어 상대를 높이는 겸양 표현이다.', translation: '내일 오후에 그쪽으로 찾아뵙겠습니다.', focus: '伺います' },
    'o-ni-naru': { explanation: '상대의 행동을 높이는 존경어 형태다.', translation: '선생님은 벌써 돌아가셨습니다.', focus: 'お帰りになりました' },
    'o-suru': { explanation: '자기 쪽의 행동을 낮추어 말하는 겸양어 형태다.', translation: '무거워 보이네요. 제가 들어 드릴까요?', focus: 'お持ちしましょうか' },
    'de-gozaimasu': { explanation: '〜です보다 격식 있게 「~입니다」라고 말한다.', translation: '화장실은 저쪽에 있습니다.' },
    'te-mo-kamawanai': { explanation: '허락하거나 허락을 구할 때 「~해도 상관없다」고 말한다.', translation: '여기에 짐을 놓아도 괜찮습니까?', focus: '構いませんか' },
    'no-koto-nominalizer': { explanation: '동작이나 문장을 명사처럼 만들어 뒤의 조사·서술어에 연결한다.', translation: '나는 사진 찍는 것을 좋아합니다.' },
    'ba-yokatta': { explanation: '하지 않은 과거 행동을 돌아보며 후회한다.', translation: '집에서 좀 더 일찍 나왔으면 좋았을 텐데.' },
    'tara-dou': { explanation: '상대에게 어떤 행동을 해 보는 것이 어떨지 가볍게 제안한다.', translation: '피곤하면 조금 쉬는 게 어때?' },
    'hou-ga-ii': { explanation: '두 선택을 비교해 더 나은 행동을 조언한다.', translation: '열이 있다면 병원에 가는 편이 좋아요.' },
    'toka-toka': { explanation: '여러 예를 가볍게 나열하며 그 밖의 것도 있음을 암시한다.', translation: '냉장고에 달걀이나 우유 같은 것이 들어 있습니다.', focus: 'とか' },
    'nado': { explanation: '대표적인 예를 들고 그 밖의 것도 포함함을 나타낸다.', translation: '책상 위에 책이나 공책 등이 있습니다.' },
    'de-mo-suggestion': { explanation: '여러 선택 중 하나를 가볍게 권하거나 제안한다.', translation: '잠깐 쉬면서 커피라도 마시지 않을래요?' },
    'sa': { explanation: '형용사를 정도나 성질을 나타내는 명사로 바꾼다.', translation: '이 다리의 길이는 얼마나 됩니까?' },
    'me': { explanation: '숫자와 함께 순서를 나타낸다.', translation: '오른쪽에서 세 번째 건물이 도서관입니다.' },
    'oki-ni': { explanation: '일정한 수량이나 시간을 간격으로 반복한다.', translation: '이 버스는 15분 간격으로 옵니다.' },
    'ku-suru-ni-suru': { explanation: '대상을 어떤 상태로 바꾸거나 그렇게 정한다.', translation: '텔레비전 소리를 작게 해 주세요.' },
    'ga-suru': { explanation: '냄새·소리·맛·느낌 등이 감각으로 느껴짐을 말한다.', translation: '부엌에서 좋은 냄새가 난다.' },
    'kana-kashira': { explanation: '스스로 궁금해하거나 가볍게 의문을 나타낸다.', translation: '내일은 날씨가 맑으려나.' },
    'te-kuremasen-ka-te-itadakemasen-ka': { explanation: '상대에게 행동을 부탁한다. 〜ていただけませんか가 더 공손하다.', translation: '죄송한데 사진을 찍어 주시겠어요?' },
    'naide': { explanation: '한 행동을 하지 않은 채 다른 행동을 한다.', translation: '오늘 아침에는 아침밥을 먹지 않고 학교에 갔다.' },
  },
  N5: {
    'wa': { explanation: '문장의 화제를 제시하는 조사다. 글자는 は지만 조사일 때는 「와」로 읽는다.', translation: '나는 학생입니다.' },
    'ga-subject': { explanation: '주어나 새롭게 강조하는 정보를 나타낸다. 의문사의 주어에도 쓴다.', translation: '비가 오고 있습니다.' },
    'o': { explanation: '동작이 직접 미치는 대상을 나타내는 조사다.', translation: '매일 아침 빵을 먹습니다.' },
    'ni-time': { explanation: '특정한 시각이나 날짜처럼 정해진 시점을 나타낸다.', translation: '매일 아침 7시에 일어납니다.' },
    'ni-destination': { explanation: '이동이 도달하는 목적지를 나타낸다.', translation: '매일 버스를 타고 학교에 갑니다.' },
    'ni-location': { explanation: '사람이나 물건이 존재하는 장소를 나타낸다.', translation: '책상 위에 사전이 있습니다.' },
    'ni-indirect-object': { explanation: '행동을 받는 상대나 도달하는 대상을 나타낸다.', translation: '어머니께 편지를 씁니다.' },
    'ni-frequency': { explanation: '정해진 기간 안에 일어나는 횟수를 나타낸다.', translation: '일주일에 두 번 수영장에서 수영합니다.' },
    'e': { explanation: '이동하는 방향을 나타낸다. 조사 へ는 「에」로 읽는다.', translation: '여름 방학에 홋카이도에 갑니다.' },
    'de-place': { explanation: '어떤 행동이 일어나는 장소를 나타낸다.', translation: '도서관에서 책을 읽습니다.' },
    'de-means': { explanation: '이동 수단이나 행동에 쓰는 도구·방법을 나타낸다.', translation: '매일 전철로 회사에 갑니다.' },
    'to-and': { explanation: '대상을 빠짐없이 나열할 때 명사 사이에 쓴다.', translation: '가방 안에 펜과 공책이 있습니다.' },
    'to-with': { explanation: '함께 행동하는 사람이나 상대를 나타낸다.', translation: '주말에 친구와 영화를 봤습니다.' },
    'ya': { explanation: '대표적인 몇 가지를 나열하며 그 밖의 것도 있음을 암시한다.', translation: '책상 위에 책이나 잡지 등이 있습니다.' },
    'ka-or': { explanation: '둘 이상의 선택지 가운데 하나를 고르게 한다.', translation: '마실 것은 커피나 홍차가 좋습니다.' },
    'mo': { explanation: '같은 성질이나 행동이 다른 대상에도 해당함을 나타낸다.', translation: '나도 학생입니다.' },
    'no': { explanation: '소유·소속·관계 등을 나타내며 명사와 명사를 연결한다.', translation: '이것은 내 우산입니다.' },
    'kara-from': { explanation: '시간이나 장소의 시작점을 나타낸다.', translation: '수업은 9시부터입니다.' },
    'made': { explanation: '시간이나 장소의 끝점을 나타낸다.', translation: '점심시간은 1시까지입니다.' },
    'ka-question': { explanation: '정중한 문장의 끝에 붙여 질문을 만든다.', translation: '이것은 당신의 가방입니까?' },
    'ne': { explanation: '상대에게 확인하거나 공감을 구하는 종조사다.', translation: '오늘은 덥네요.' },
    'yo': { explanation: '상대에게 새 정보를 알려 주거나 내용을 강조하는 종조사다.', translation: '이 라멘은 정말 맛있어요.' },
    'yori': { explanation: '둘을 비교할 때 기준이 되는 대상을 나타낸다.', translation: '오늘은 어제보다 춥습니다.' },
    'no-hou-ga-yori': { explanation: '두 대상을 비교해 어느 쪽이 더 그러한지 말한다.', translation: '나는 고양이보다 개를 더 좋아합니다.', focus: 'の方が' },
    'to-to-dochira-ga': { explanation: '둘 중 어느 쪽인지 비교해서 묻는다.', translation: '커피와 홍차 중 어느 쪽을 더 좋아합니까?', focus: 'とどちらが' },
    'no-naka-de-ga-ichiban': { explanation: '여러 대상 가운데 가장 높은 정도를 나타낸다.', translation: '과일 중에서 사과를 가장 좋아합니다.', focus: 'の中で' },
    'desu': { explanation: '명사나 な형용사 뒤에 붙여 현재의 상태를 정중하게 말한다.', translation: '저는 마리아입니다.' },
    'da': { explanation: '명사나 な형용사 뒤에 붙이는 보통체 서술 표현이다.', translation: '오늘은 일요일이다.' },
    'de-wa-arimasen-ja-nai': { explanation: '명사·な형용사를 부정한다. じゃない는 더 일상적인 형태다.', translation: '저는 선생님이 아닙니다. 학생입니다.' },
    'deshita': { explanation: '명사·な형용사의 과거 상태를 정중하게 말한다.', translation: '어제는 제 생일이었습니다.' },
    'masu': { explanation: '동작의 현재·미래를 정중하게 말하는 동사 어미다.', translation: '매일 아침 커피를 마십니다.' },
    'masen': { explanation: '동작을 하지 않음을 정중하게 나타내는 동사 어미다.', translation: '저는 술을 마시지 않습니다.' },
    'mashita': { explanation: '이미 한 동작을 정중하게 말하는 과거형이다.', translation: '어제 친구를 만났습니다.' },
    'masen-deshita': { explanation: '과거에 동작을 하지 않았음을 정중하게 말한다.', translation: '오늘 아침에는 아침밥을 먹지 않았습니다.' },
    'nai': { explanation: '동작을 하지 않음을 나타내는 보통체 부정형이다.', translation: '오늘은 학교에 가지 않는다.' },
    'ta': { explanation: '이미 일어난 동작을 나타내는 보통체 과거형이다.', translation: '주말에는 집에서 영화를 봤다.' },
    'mashou': { explanation: '상대와 함께할 행동을 정중하게 제안한다.', translation: '함께 갑시다.' },
    'mashou-ka': { explanation: '자신이 도와줄지를 묻거나 함께할 행동을 제안한다.', translation: '창문을 열까요?' },
    'masen-ka': { explanation: '상대에게 함께할 행동을 정중하게 권한다.', translation: '같이 점심을 먹지 않겠어요?' },
    'tai': { explanation: '말하는 사람의 하고 싶은 마음을 나타낸다.', translation: '여름 방학에 오키나와에 가고 싶습니다.' },
    'ga-hoshii': { explanation: '원하는 물건이나 대상을 나타낸다.', translation: '새 컴퓨터가 갖고 싶습니다.' },
    'o-kudasai': { explanation: '물건을 달라고 정중하게 요청한다.', translation: '죄송하지만 물 좀 주세요.' },
    'te-kudasai': { explanation: '상대에게 행동을 해 달라고 정중하게 요청한다.', translation: '조금 더 천천히 말해 주세요.' },
    'naide-kudasai': { explanation: '상대에게 행동을 하지 말라고 정중하게 요청한다.', translation: '교실에서 먹지 말아 주세요.' },
    'te-mo-ii': { explanation: '허락받거나 어떤 행동이 허용됨을 나타낸다.', translation: '이 사전을 사용해도 됩니까?' },
    'te-wa-ikenai': { explanation: '어떤 행동을 금지할 때 쓴다.', translation: '도서관에서 큰 소리로 말하면 안 됩니다.' },
    'nakereba-naranai-nakute-wa-ikenai': { explanation: '해야 하는 의무나 필요를 나타낸다.', translation: '내일은 6시에 일어나야 합니다.' },
    'nakute-mo-ii': { explanation: '어떤 행동을 하지 않아도 괜찮음을 나타낸다.', translation: '내일은 학교에 오지 않아도 됩니다.' },
    'te-iru': { explanation: '동작이 진행 중이거나 그 결과가 유지되는 상태를 나타낸다.', translation: '남동생은 지금 방에서 게임을 하고 있습니다.' },
    'te': { explanation: '두 동작을 순서대로 이어 말한다.', translation: '아침에 일어나서 세수를 합니다.' },
    'te-kara': { explanation: '앞의 행동을 마친 뒤 다음 행동을 함을 나타낸다.', translation: '손을 씻은 뒤 밥을 먹읍시다.' },
    'tari-tari-suru': { explanation: '대표적인 행동 몇 가지를 나열하고 그 밖의 행동도 있음을 암시한다.', translation: '일요일에는 청소하거나 빨래하는 등의 일을 합니다.', focus: 'したり' },
    'ta-koto-ga-aru': { explanation: '과거에 어떤 일을 경험한 적이 있음을 나타낸다.', translation: '후지산에 올라가 본 적이 있습니다.' },
    'mae-ni': { explanation: '어떤 행동이나 시점보다 앞을 나타낸다.', translation: '자기 전에 이를 닦습니다.' },
    'ato-de': { explanation: '어떤 행동이나 시점이 지난 뒤를 나타낸다.', translation: '저녁을 먹은 뒤 산책합니다.' },
    'nagara': { explanation: '두 행동을 동시에 할 때 동사 ます형 어간에 붙인다.', translation: '음악을 들으면서 공부합니다.' },
    'ni-iku': { explanation: '어떤 행동을 목적으로 이동함을 나타낸다.', translation: '옷을 사러 백화점에 갑니다.', focus: '買いに行きます' },
    'ga-suki-ga-kirai': { explanation: '좋아하거나 싫어하는 대상을 が로 표시한다.', translation: '저는 단것을 좋아합니다.' },
    'ga-jouzu-ga-heta': { explanation: '잘하거나 못하는 대상을 が로 표시한다.', translation: '언니는 피아노를 잘 칩니다.' },
    'ga-aru-ga-iru': { explanation: '사물에는 ある, 사람·동물에는 いる를 써서 존재를 말한다.', translation: '공원에 큰 나무가 있습니다.' },
    'kara-reason': { explanation: '앞 문장을 뒤 문장의 이유로 제시한다.', translation: '오늘은 추우니까 코트를 입습니다.' },
    'ga-but': { explanation: '앞뒤 내용을 부드럽게 대조해 연결한다.', translation: '이 가게는 저렴하지만 음식이 별로 맛있지 않습니다.' },
    'deshou': { explanation: '확신하지 않는 미래나 상황을 정중하게 추측한다.', translation: '내일은 비가 오겠지요.' },
    'ku-naru-ni-naru': { explanation: '형용사 뒤에 붙여 상태의 변화를 나타낸다.', translation: '따뜻해졌네요.' },
    'ni-suru': { explanation: '여러 선택지 가운데 하나를 선택하거나 결정한다.', translation: '저는 카레로 할게요.' },
    'mada-te-inai': { explanation: '기대되는 일이 지금까지 일어나지 않았음을 나타낸다.', translation: '아직 점심을 먹지 않았습니다.', focus: '食べていません' },
    'mou-ta': { explanation: '이미 끝난 일을 나타낸다.', translation: '「벌써 저녁을 먹었어요?」 「네, 이미 먹었어요.」', focus: 'もう食べました' },
    'amari-nai': { explanation: '부정형과 함께 쓰여 정도나 횟수가 많지 않음을 나타낸다.', translation: '저는 텔레비전을 별로 보지 않습니다.', focus: 'あまり' },
    'zenzen-nai': { explanation: '부정형과 함께 쓰여 전혀 그렇지 않음을 강조한다.', translation: '이 문제는 전혀 모르겠습니다.', focus: '全然わかりません' },
    'dake': { explanation: '대상의 범위가 그것 하나로 제한됨을 나타낸다.', translation: '지갑에 100엔만 있습니다.' },
    'kurai-gurai': { explanation: '대략적인 수량·시간·정도를 나타낸다.', translation: '역까지 걸어서 10분 정도입니다.' },
    'goro': { explanation: '정확하지 않은 대략적인 시각을 나타낸다.', translation: '매일 밤 11시쯤 잡니다.' },
    'nani-mo-nai-dare-mo-nai': { explanation: '의문사 뒤에 も와 부정형을 붙여 아무것도·아무도 없음을 나타낸다.', translation: '오늘 아침에는 아무것도 먹지 않았습니다.', focus: '何も' },
    'nani-ka-dare-ka-doko-ka': { explanation: '의문사에 か를 붙여 불특정한 대상이나 장소를 나타낸다.', translation: '뭔가 마시겠습니까?' },
    'kore-sore-are-dore': { explanation: '말하는 사람과 듣는 사람에게서의 거리에 따라 이것·그것·저것·어느 것을 가리킨다.', translation: '이것은 제 사전입니다.' },
    'kono-sono-ano-dono': { explanation: '뒤의 명사를 꾸미며 이·그·저·어느 대상을 가리킨다.', translation: '이 케이크는 맛있습니다.' },
    'koko-soko-asoko-doko': { explanation: '말하는 사람과 듣는 사람의 위치를 기준으로 여기·거기·저기·어디를 가리킨다.', translation: '여기는 제 학교입니다.' },
    'ku-nai-katta-ku-nakatta': { explanation: 'い형용사의 부정·과거·과거 부정 형태를 구별한다.', translation: '이 방은 별로 넓지 않습니다.' },
    'na-na-adjective': { explanation: 'な형용사로 명사를 꾸밀 때는 な를 붙인다.', translation: '교토는 유명한 도시입니다.' },
    'kute-de': { explanation: '형용사나 명사의 성질을 뒤 문장과 연결한다.', translation: '이 가게는 싸고 맛있습니다.' },
    'to-iu-named': { explanation: '이름이나 명칭을 소개할 때 「~라고 하는」이라는 뜻으로 쓴다.', translation: '이것은 「스키야키」라는 요리입니다.' },
  },
};
